name: Bug Report
description: Report a reproducible bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug, including expected and actual behavior
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps to reproduce the bug
      placeholder: |
        1. Run `blueprint ...`
        2. Enter `...`
        3. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details (OS, runtime, etc).
      placeholder: "`node -v && uname -a` e.g., Ubuntu 25.04, Node 22.16.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Include relevant logs, stack traces, or screenshots
    validations:
      required: false
