name: Docs Update
description: Suggest an update or improvement to the documentation
labels: ["documentation"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Update
      description: Describe the proposed documentation update or fix
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other relevant information or context
    validations:
      required: false
