name: Feature Request
description: Suggest an idea or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Clearly describe the feature you’d like to see added
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Explain why this feature is useful or what problem it solves
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots here
    validations:
      required: false
