name: Reward merged PRs

on:
  workflow_dispatch:
    inputs:
      per_page:
        description: 'Number of merged PRs to process'
        required: false
        default: '15000'  # Default value shown in UI
        type: string

jobs:
  reward:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ton-society/gh-ton-contribution-reward/.github/actions/rewards-for-merged-prs@v1
        with:
          per_page: ${{ inputs.per_page }}
          activity_id: '9747'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          x_api_key: ${{ secrets.X_API_KEY }}
          x_partner_id: ${{ secrets.X_PARTNER_ID }}
