name: Reward

on:
  push:
    branches:
      - main
      - develop

jobs:
  reward:
    name: Reward
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ton-society/gh-ton-contribution-reward@v1
        with:
          activity_id: '9747'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          x_api_key: ${{ secrets.X_API_KEY }}
          x_partner_id: ${{ secrets.X_PARTNER_ID }}
